name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Send Slack Message (Start)
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Deployment started :progress_bar: :fingerscrossed:"}' \
          'https://hooks.slack.com/services/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'

      - name: Notify Slack (Complete)
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "CI Deploy completed for repo <https://github.com/${{ github.repository }}|${{ github.repository }}> on branch ${{ github.ref }}.\nStatus: ${{ job.status }}\nBuild number: ${{ env.VERSION }}"
            }
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'

      - name: Notify Slack on Job Status (Always)
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Job Status: ${{ job.status }}"}' \
          'https://hooks.slack.com/services/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'
